export enum SlotType {
    HEAD = "head",
    BODY = "body",
    BELT = "belt",
    GLOVES = "gloves",
    LEGS = "legs",
    BOOTS = "boots",
    NECKLACE = "necklace",
    RING_1 = "ring1",
    RING_2 = "ring2",
    MAIN_HAND = "main_hand",
    SECOND_HAND = "second_hand",
    BULLET = "bullet",
    RING = "RING",
}
